# Ansible Playbook

- hosts: fmc
  connection: httpapi
  gather_facts: False
  tasks:
    - name: Get Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain
